server:
  port: ${APP_PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    ROOT: INFO
    com.spring: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

thread:
  corePoolSize: 4
  maxPoolSize: 8

garage:
  diagnostics:
    price: 500