version: '2'
services:
  postgres:
    image: postgres:11.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5440:5432
#docker>docker-compose up -d
#docker>docker-compose down --remove-orphans